### PR TITLE
squash test

### PR DESCRIPTION
**Pull request by staticvoidjb**
Would like to practice squashing please.

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
I'm very happy that finally someone made a PR with a goal. Bravo! Ok. lets do this!

**Comment by grayghostvisuals** [comment]
@staticvoidjb Before we start I'd like you to read over this [article](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) that will help.

Note: This will all be done on your end of course.

**Comment by staticvoidjb** [comment]
Hi Grey Ghost. Not sure if it notifies you that the pull request is different now(?)

If it's ok, I'd like to do some more fiddling around including maybe even you forking an example repo that I create at some point?  - I'm learning alot and very, very grateful.

**Comment by grayghostvisuals** [comment]
Here is how I see the PR from my end. Also its grAy ghost with an A ;)
screenshot 2017-10-17 09 29 12

Here's the commit I'm looking at https://github.com/grayghostvisuals/practice-git/pull/81/commits/b20c9095d29f797475ea47c1013cbd40e7670c01. LMK if that looks right to you and I'll go ahead and merge in this PR.

**Comment by staticvoidjb** [comment]
Yes. Please merge. Thank you!

**Pull request merged**
