### PR TITLE
added pi-program

### PR DESCRIPTION
**Pull request by heptocat**
Yay :) first pull request made the hard way (using git)

### CODE REVIEW

**Comment by heptocat** [comment]
I do not understand this: It says a certain danburg created the program… who is danburg? I created the program myself and added it to my local repository.

**Comment by grayghostvisuals** [comment]
@heptocat Not following. Can you provide a link or screenshot to help me better understand your concern?

**Comment by grayghostvisuals** [comment]
@danburg I hope you are having fun because you have been reported to GitHub.

**Comment by heptocat** [comment]
Wit danburg do you mean me? Or do you think someone is using my account? Did I do something wrong :/ ?

**Comment by grayghostvisuals** [comment]
I'm going to close this commit. Sorry

**Comment by grayghostvisuals** [comment]
@heptocat I would try to copy your file to a new fork of this repo and resubmit your PR

**Pull request closed without merging**
