### PR TITLE
Added Link to README

### PR DESCRIPTION
**Pull request by deramsey**
Added link for Git Hot Tips by Wes Bos as reference in issue #42

### CODE REVIEW

**Comment by grayghostvisuals** [comment]
@deramsey Hot tip: when u wanna close an issue through a commit once its merged just put "closes #[issue-number]" in your commit message 👍

**Comment by 455711** [comment]
Mon Lay

**Comment by 455711** [comment]
Xboxry77

**Comment by 455711** [comment]
meeting

**Comment by 455711** [comment]
1502

**Comment by 455711** [comment]
branch1502/test-file.txt

**Comment by 455711** [comment]
455711

**Pull request merged**
